// Code generated by entc, DO NOT EDIT.

package servicetwitch

const (
	// Label holds the string label denoting the servicetwitch type in the database.
	Label = "service_twitch"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccessToken holds the string denoting the access_token field in the database.
	FieldAccessToken = "access_token"
	// FieldRefreshToken holds the string denoting the refresh_token field in the database.
	FieldRefreshToken = "refresh_token"
	// FieldScopes holds the string denoting the scopes field in the database.
	FieldScopes = "scopes"
	// Table holds the table name of the servicetwitch in the database.
	Table = "service_twitches"
)

// Columns holds all SQL columns for servicetwitch fields.
var Columns = []string{
	FieldID,
	FieldAccessToken,
	FieldRefreshToken,
	FieldScopes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
