// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"hypebase/ent/predicate"
	"hypebase/ent/usersession"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserSessionDelete is the builder for deleting a UserSession entity.
type UserSessionDelete struct {
	config
	hooks    []Hook
	mutation *UserSessionMutation
}

// Where adds a new predicate to the UserSessionDelete builder.
func (usd *UserSessionDelete) Where(ps ...predicate.UserSession) *UserSessionDelete {
	usd.mutation.predicates = append(usd.mutation.predicates, ps...)
	return usd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (usd *UserSessionDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(usd.hooks) == 0 {
		affected, err = usd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserSessionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			usd.mutation = mutation
			affected, err = usd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(usd.hooks) - 1; i >= 0; i-- {
			mut = usd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, usd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (usd *UserSessionDelete) ExecX(ctx context.Context) int {
	n, err := usd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (usd *UserSessionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: usersession.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usersession.FieldID,
			},
		},
	}
	if ps := usd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, usd.driver, _spec)
}

// UserSessionDeleteOne is the builder for deleting a single UserSession entity.
type UserSessionDeleteOne struct {
	usd *UserSessionDelete
}

// Exec executes the deletion query.
func (usdo *UserSessionDeleteOne) Exec(ctx context.Context) error {
	n, err := usdo.usd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usersession.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (usdo *UserSessionDeleteOne) ExecX(ctx context.Context) {
	usdo.usd.ExecX(ctx)
}
