// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ServiceTwitch is the predicate function for servicetwitch builders.
type ServiceTwitch func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserSession is the predicate function for usersession builders.
type UserSession func(*sql.Selector)
